project_id = "mpsusvpdjuqvjgdsvwpp"

[functions.import-images]
verify_jwt = false

[functions.generate-blog-seo]
verify_jwt = false

[functions.generate-invoices]
verify_jwt = false

[functions.mark-overdue-invoices]
verify_jwt = false